name: WorkflowIndexer
description: XOXO
networks:
  - id: 11155420
    start_block: 0
    contracts:
      - name: ModuleFactory_v1
        abi_file_path: abis/ModuleFactory_v1.json
        address: 0xAEa18210Bb38E27E7483410D183F8DAef7E93d04
        handler: src/factories/mapping.ts
        events:
          - event: ModuleCreated
          - event: MetadataRegistered
      - name: OrchestratorFactory_v1
        abi_file_path: abis/OrchestratorFactory_v1.json
        address: 0x37BeDeBbA1E0278f4126249735f04ED80c066CbE
        handler: src/factories/mapping.ts
        events:
          - event: OrchestratorCreated
      - name: Orchestrator_v1
        abi_file_path: abis/Orchestrator_v1.json
        address:
        handler: src/factories/mapping.ts
        events:
          - event: OrchestratorInitialized
      - name: FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1
        abi_file_path: abis/FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1.json
        address:
        handler: src/fundingManager/mapping.ts
        events:
          - event: ModuleInitialized
          - event: BuyFeeUpdated
          - event: SellFeeUpdated
          - event: BuyReserveRatioSet
          - event: SellReserveRatioSet
          - event: IssuanceTokenUpdated
          - event: CollateralTokenSet
          - event: TokensBought
          - event: TokensSold
