name: Inverter Protocol Indexer
description: Indexes events from the Inverter Protocol
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - 'hash'
contracts:
  - name: ModuleFactory_v1
    abi_file_path: abis/ModuleFactory_v1.json
    handler: src/mappings/factory/module.ts
    events:
      - event: ModuleCreated
      - event: MetadataRegistered
  - name: OrchestratorFactory_v1
    abi_file_path: abis/OrchestratorFactory_v1.json
    handler: src/mappings/factory/orchestrator.ts
    events:
      - event: OrchestratorCreated
  - name: Migrating_PIM_Factory_v1
    abi_file_path: abis/Migrating_PIM_Factory_v1.json
    handler: src/mappings/factory/migrating.ts
    events:
      - event: Graduation
      - event: PIMWorkflowCreated
  - name: Orchestrator_v1
    abi_file_path: abis/Orchestrator_v1.json
    handler: src/mappings/factory/orchestrator.ts
    events:
      - event: OrchestratorInitialized
  - name: AUT_Roles_v1
    abi_file_path: abis/AUT_Roles_v1.json
    handler: src/mappings/authorizer/aut-roles.ts
    events:
      - event: ModuleInitialized
      - event: RoleAdminChanged
      - event: RoleGranted
      - event: RoleRevoked
  - name: BondingCurve # renamed to solve postgres conflict due to length of name
    abi_file_path: abis/FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1.json
    handler: src/mappings/funding-manager/bonding-curve/index.ts
    events:
      - event: ModuleInitialized
      - event: BuyFeeUpdated
      - event: SellFeeUpdated
      - event: BuyReserveRatioSet
      - event: SellReserveRatioSet
      - event: TokensBought
      - event: TokensSold
      - event: VirtualIssuanceSupplySet
      - event: VirtualIssuanceAmountAdded
      - event: VirtualIssuanceAmountSubtracted
      - event: VirtualCollateralSupplySet
      - event: VirtualCollateralAmountAdded
      - event: VirtualCollateralAmountSubtracted
      - event: ProjectCollateralFeeWithdrawn
      - event: ProtocolFeeMinted
      - event: ProtocolFeeTransferred
  - name: PP_Streaming_v1
    abi_file_path: abis/PP_Streaming_v1.json
    handler: src/mappings/payment-processor/streaming.ts
    events:
      - event: ModuleInitialized
      - event: StreamingPaymentAdded
  - name: LM_PC_Bounties_v1
    abi_file_path: abis/LM_PC_Bounties_v1.json
    handler: src/mappings/logic-module/bounties.ts
    events:
      - event: ModuleInitialized
      - event: BountyAdded
      - event: BountyUpdated
      - event: BountyLocked
      - event: ClaimAdded
      - event: ClaimContributorsUpdated
      - event: ClaimDetailsUpdated
      - event: ClaimVerified
  - name: FM_DepositVault_v1
    abi_file_path: abis/FM_DepositVault_v1.json
    handler: src/mappings/funding-manager/deposit-vault.ts
    events:
      - event: ModuleInitialized
      - event: Deposit
      - event: TransferOrchestratorToken
  - name: FM_PC_ExternalPrice_Redeeming_v1
    abi_file_path: abis/FM_PC_ExternalPrice_Redeeming_v1.json
    handler: src/mappings/funding-manager/oracle-price/index.ts
    events:
      - event: ModuleInitialized
      - event: ProjectTreasuryUpdated
      - event: BuyFeeUpdated
      - event: SellFeeUpdated
      - event: TokensBought
      - event: TokensSold
      - event: ProjectCollateralFeeAdded
      - event: ProtocolFeeMinted
      - event: ProtocolFeeTransferred
      - event: RedemptionAmountUpdated
      - event: PaymentOrderAdded
      - event: OracleUpdated
      - event: ReserveDeposited
      - event: IssuanceTokenSet
  - name: PP_Queue_v1
    abi_file_path: abis/PP_Queue_v1.json
    handler: src/mappings/payment-processor/queue.ts
    events:
      - event: PaymentOrderQueued
      - event: PaymentOrderStateChanged
      - event: PaymentQueueExecuted
  - name: PP_Queue_ManualExecution_v1
    abi_file_path: abis/PP_Queue_ManualExecution_v1.json
    handler: src/mappings/payment-processor/queue-manual-execution.ts
    events:
      - event: PaymentOrderQueued
      - event: PaymentOrderStateChanged
      - event: PaymentQueueExecuted
  - name: LM_ManualExternalPriceSetter_v1
    abi_file_path: abis/LM_ManualExternalPriceSetter_v1.json
    handler: src/mappings/logic-module/manual-external-price-setter.ts
    events:
      - event: ModuleInitialized
      - event: IssuancePriceSet
      - event: RedemptionPriceSet
  - name: ERC20Issuance_Blacklist_v1
    abi_file_path: abis/ERC20Issuance_Blacklist_v1.json
    handler: src/mappings/token/issuance-blacklist.ts
    events:
      - event: AddedToBlacklist
      - event: RemovedFromBlacklist
      - event: BlacklistManagerUpdated
      - event: MinterSet
networks:
  - id: 11155420
    start_block: 16141643
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: AUT_Roles_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
      - name: FM_PC_ExternalPrice_Redeeming_v1
        address:
      - name: PP_Queue_v1
        address:
      - name: PP_Queue_ManualExecution_v1
        address:
      - name: LM_ManualExternalPriceSetter_v1
        address:
      - name: ERC20Issuance_Blacklist_v1
        address:
  - id: 84532
    start_block: 14158776
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: AUT_Roles_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
      - name: FM_PC_ExternalPrice_Redeeming_v1
        address:
      - name: PP_Queue_v1
        address:
      - name: PP_Queue_ManualExecution_v1
        address:
      - name: LM_ManualExternalPriceSetter_v1
        address:
      - name: ERC20Issuance_Blacklist_v1
        address:
  - id: 1101
    start_block: 16657460
    contracts:
      - name: ModuleFactory_v1
        address: 0x5Da8231feE106f4A43e07f2EEE95564467A1Ee58
      - name: OrchestratorFactory_v1
        address: 0x6ecA5f791d9635e4a1874cCD95564F914fBCF73d
      - name: Orchestrator_v1
        address:
      - name: AUT_Roles_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
      - name: FM_PC_ExternalPrice_Redeeming_v1
        address:
      - name: PP_Queue_v1
        address:
      - name: PP_Queue_ManualExecution_v1
        address:
      - name: LM_ManualExternalPriceSetter_v1
        address:
      - name: ERC20Issuance_Blacklist_v1
        address:
  - id: 11155111
    start_block: 6531547
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: Migrating_PIM_Factory_v1
        address: 0xd9efea12ff508ea3bd6e67d185387d71f83f4ad1
      - name: AUT_Roles_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
      - name: FM_PC_ExternalPrice_Redeeming_v1
        address:
      - name: PP_Queue_v1
        address:
      - name: PP_Queue_ManualExecution_v1
        address:
      - name: LM_ManualExternalPriceSetter_v1
        address:
      - name: ERC20Issuance_Blacklist_v1
        address:
  - id: 137
    start_block: 67830000
    contracts:
      - name: ModuleFactory_v1
        address: 0x5Da8231feE106f4A43e07f2EEE95564467A1Ee58
      - name: OrchestratorFactory_v1
        address: 0x6ecA5f791d9635e4a1874cCD95564F914fBCF73d
      - name: Orchestrator_v1
        address:
      - name: AUT_Roles_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
      - name: FM_PC_ExternalPrice_Redeeming_v1
        address:
      - name: PP_Queue_v1
        address:
      - name: PP_Queue_ManualExecution_v1
        address:
      - name: LM_ManualExternalPriceSetter_v1
        address:
      - name: ERC20Issuance_Blacklist_v1
        address:
  - id: 80002
    start_block: 14158776
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: AUT_Roles_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
      - name: FM_PC_ExternalPrice_Redeeming_v1
        address:
      - name: PP_Queue_v1
        address:
      - name: PP_Queue_ManualExecution_v1
        address:
      - name: LM_ManualExternalPriceSetter_v1
        address:
      - name: ERC20Issuance_Blacklist_v1
        address:
