name: Inverter Protocol Indexer
description: Indexes events from the Inverter Protocol
unordered_multichain_mode: true
rollback_on_reorg: false
contracts:
  - name: ModuleFactory_v1
    abi_file_path: abis/ModuleFactory_v1.json
    handler: src/mappings/factory/module.ts
    events:
      - event: ModuleCreated
      - event: MetadataRegistered
  - name: OrchestratorFactory_v1
    abi_file_path: abis/OrchestratorFactory_v1.json
    handler: src/mappings/factory/orchestrator.ts
    events:
      - event: OrchestratorCreated
  - name: Orchestrator_v1
    abi_file_path: abis/Orchestrator_v1.json
    handler: src/mappings/factory/orchestrator.ts
    events:
      - event: OrchestratorInitialized
  - name: BondingCurve # renamed to solve postgres conflict due to length of name
    abi_file_path: abis/FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1.json
    handler: src/mappings/funding-manager/bonding-curve/index.ts
    events:
      - event: ModuleInitialized
      - event: BuyFeeUpdated
      - event: SellFeeUpdated
      - event: BuyReserveRatioSet
      - event: SellReserveRatioSet
      - event: OrchestratorTokenSet
      - event: IssuanceTokenSet
      - event: TokensBought
      - event: TokensSold
      - event: VirtualIssuanceSupplySet
      - event: VirtualIssuanceAmountAdded
      - event: VirtualIssuanceAmountSubtracted
      - event: VirtualCollateralSupplySet
      - event: VirtualCollateralAmountAdded
      - event: VirtualCollateralAmountSubtracted
      - event: ProjectCollateralFeeWithdrawn
      - event: ProtocolFeeMinted
      - event: ProtocolFeeTransferred
  - name: PP_Streaming_v1
    abi_file_path: abis/PP_Streaming_v1.json
    handler: src/mappings/payment-processor/streaming.ts
    events:
      - event: ModuleInitialized
      - event: StreamingPaymentAdded
  - name: LM_PC_Bounties_v1
    abi_file_path: abis/LM_PC_Bounties_v1.json
    handler: src/mappings/logic-module/bounties.ts
    events:
      - event: ModuleInitialized
      - event: BountyAdded
      - event: BountyUpdated
      - event: BountyLocked
      - event: ClaimAdded
      - event: ClaimContributorsUpdated
      - event: ClaimDetailsUpdated
      - event: ClaimVerified
  - name: FM_DepositVault_v1
    abi_file_path: abis/FM_DepositVault_v1.json
    handler: src/mappings/funding-manager/deposit-vault.ts
    events:
      - event: ModuleInitialized
      - event: Deposit
      - event: TransferOrchestratorToken
networks:
  - id: 11155420
    start_block: 16141643
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
  - id: 84532
    start_block: 14158776
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
  - id: 1101
    start_block: 16657460
    contracts:
      - name: ModuleFactory_v1
        address: 0x5Da8231feE106f4A43e07f2EEE95564467A1Ee58
      - name: OrchestratorFactory_v1
        address: 0x6ecA5f791d9635e4a1874cCD95564F914fBCF73d
      - name: Orchestrator_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
  - id: 11155111
    start_block: 6531547
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_Bounties_v1
        address:
      - name: FM_DepositVault_v1
        address:
