name: Inverter Protocol Indexer
description: Indexes events from the Inverter Protocol
contracts:
  - name: ModuleFactory_v1
    abi_file_path: abis/ModuleFactory_v1.json
    handler: src/factories/mapping.ts
    events:
      - event: ModuleCreated
      - event: MetadataRegistered
  - name: OrchestratorFactory_v1
    abi_file_path: abis/OrchestratorFactory_v1.json
    handler: src/factories/mapping.ts
    events:
      - event: OrchestratorCreated
  - name: Orchestrator_v1
    abi_file_path: abis/Orchestrator_v1.json
    handler: src/factories/mapping.ts
    events:
      - event: OrchestratorInitialized
  - name: BondingCurve # renamed to solve postgres conflict due to length of name
    abi_file_path: abis/FM_BC_Restricted_Bancor_Redeeming_VirtualSupply_v1.json
    handler: src/fundingManager/mapping.ts
    events:
      - event: ModuleInitialized
      - event: BuyFeeUpdated
      - event: SellFeeUpdated
      - event: BuyReserveRatioSet
      - event: SellReserveRatioSet
      - event: OrchestratorTokenSet
      - event: IssuanceTokenSet
      - event: TokensBought
      - event: TokensSold
      - event: VirtualIssuanceSupplySet
      - event: VirtualIssuanceAmountAdded
      - event: VirtualIssuanceAmountSubtracted
      - event: VirtualCollateralSupplySet
      - event: VirtualCollateralAmountAdded
      - event: VirtualCollateralAmountSubtracted
      - event: ProjectCollateralFeeWithdrawn
  - name: PP_Streaming_v1
    abi_file_path: abis/PP_Streaming_v1.json
    handler: src/paymentProcessor/mapping.ts
    events:
      - event: ModuleInitialized
      - event: StreamingPaymentAdded
  - name: LM_PC_PaymentRouter_v1
    abi_file_path: abis/LM_PC_PaymentRouter_v1.json
    handler: src/logicModule/mapping.ts
    events:
      - event: ModuleInitialized
networks:
  - id: 11155420
    start_block: 0
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_PaymentRouter_v1
        address:
  - id: 84532
    start_block: 0
    contracts:
      - name: ModuleFactory_v1
        address: 0xcEB82D3FA367cE3563e07763765bB1ae7B5Ba3d5
      - name: OrchestratorFactory_v1
        address: 0x535BdbC1D369d43fed8546024D273eE5274fFF65
      - name: Orchestrator_v1
        address:
      - name: BondingCurve # renamed to solve postgres conflict due to length of name
        address:
      - name: PP_Streaming_v1
        address:
      - name: LM_PC_PaymentRouter_v1
        address:
