export const publicAggregationTables = [
  'RedemptionPaymentOrder',
  'OraclePriceFM',
  'BondingCurve',
  'IssuanceTokenDayData',
  'IssuanceTokenHourData',
  'CurveDayData',
  'CurveHourData',
  'Token',
  'Deposit',
  'DepositVault',
  'Bounty',
  'BountyClaim',
  'ProjectFee',
  'ProtocolFee',
  'Transfer',
]
