name: WorkflowIndexer
description: XOXO
networks:
  - id: 11155420
    start_block: 0
    contracts:
      - name: ModuleFactory_v1
        abi_file_path: abis/ModuleFactory_v1.json
        address: 0x3a1e656439CACd7e8b4271b217E0ca52Fef422cb
        handler: src/EventHandlers.js
        events:
          - event: ModuleCreated
          - event: MetadataRegistered
      - name: OrchestratorFactory_v1
        abi_file_path: abis/OrchestratorFactory_v1.json
        address: 0xB191a640cF7ba5D15a09C18A544a51fDBc69F442
        handler: src/EventHandlers.js
        events:
          - event: OrchestratorCreated
      - name: Orchestrator_v1
        abi_file_path: abis/Orchestrator_v1.json
        address:
        handler: src/EventHandlers.js
        events:
          - event: OrchestratorInitialized (uint indexed orchestratorId_, address fundingManager, address authorizer, address paymentProcessor, address[] modules, address governor)
