services:
  altair:
    restart: always
    container_name: altair
    image: appwrite/altair:0.3.0
    ports:
      - 3000:3000
    depends_on:
      - graphql-engine
    environment:
      SERVER_URL: http://graphql-engine:8080/v1/graphql
    networks:
      - my-proxy-net
