export const DEFAULT_GRAPHQL_URL =
  'https://dev.indexer.inverter.network/v1/graphql'

export const KNOWN_ROLE_NAMES = [
  'CURVE_INTERACTION_ROLE',
  'DEFAULT_ADMIN_ROLE',
  'CURVE_USER',
  'WHITELIST_ROLE',
  'ISSUER',
  'BOUNTY_ISSUER',
  'CLAIMANT',
  'VERIFIER_ROLE',
  'VERIFIER',
  'CLAIMANT_ROLE',
  'PRICE_SETTER_ROLE',
  'PRICE_SETTER',
  'ASSERTER_ROLE',
  'ASSERTER',
  'PAYMENT_PUSHER_ROLE',
  'PAYMENT_PUSHER',
  'WHITELIST_ROLE',
  'PRICE_SETTER_ROLE_ADMIN',
  'QUEUE_EXECUTOR_ROLE_ADMIN',
  'QUEUE_EXECUTOR_ROLE',
]
