export const bondingCurve = {
  id: undefined,
  bcType: undefined,
  orchestrator: undefined,
  buyFee: undefined,
  sellFee: undefined,
  virtualCollateral: undefined,
  virtualIssuance: undefined,
  buyReserveRatio: undefined,
  sellReserveRatio: undefined,
  issuanceToken: undefined,
  issuanceTokenDecimals: undefined,
  collateralToken: undefined,
  collateralTokenDecimals: undefined,
  recipient: undefined,
  buyer: undefined,
  bondingCurve_id: undefined,
};

export const swap = {
  id: undefined,
  swapType: undefined,
  bondingCurve_id: undefined,
  issuanceAmount: undefined,
  issuanceToken: undefined,
  collateralAmount: undefined,
  collateralToken: undefined,
  initiator: undefined,
  recipient: undefined,
  priceInCol: undefined,
  blockTimestamp: undefined,
};
