name: Dev CI-CD
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Please select your command'
        type: choice
        options:
          - UPDATE
          - MIGRATE
          - FRESH
          - SETUP
      build:
        description: 'Build new image'
        type: boolean
        default: true
env:
  REGION: eu-central-1
  PLATFORM: dev

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  build:
    name: Build
    if: inputs.build == true
    runs-on: ubuntu-latest
    environment: development
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.ACCOUNT_ID_DEV}}:role/platform-github-action-role-${{env.PLATFORM}}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Check if image exists
        id: check-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPO_NAME }}-${{env.PLATFORM}}
        run: |
          LATEST_TAG="${{env.PLATFORM}}-${GITHUB_SHA::8}"
          if aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$LATEST_TAG 2>/dev/null; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set image tag
        id: set-image-tag
        run: |
          if [[ "${{ steps.check-image.outputs.image_exists }}" == "true" ]]; then
            echo "image_tag=${{env.PLATFORM}}-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          else
            LATEST_SHA=$(git rev-parse HEAD)
            echo "image_tag=${{env.PLATFORM}}-${LATEST_SHA::8}" >> $GITHUB_OUTPUT
          fi

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        if: steps.check-image.outputs.image_exists == 'false'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPO_NAME }}-${{env.PLATFORM}}
          COMMAND: ${{ inputs.env }}
        run: |
          docker build --build-arg COMMAND_TYPE=$COMMAND -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set-image-tag.outputs.image_tag }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.set-image-tag.outputs.image_tag }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: 'n-platform-deployments'
          config: .github/config/slack.yml
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always() && !cancelled()
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.ACCOUNT_ID_DEV}}:role/platform-github-action-role-${{env.PLATFORM}}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 1200

      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Get latest image tag
        id: get-image
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
          if [[ "${{ inputs.build }}" == "true" ]]; then
            echo "IMAGE_TAG=${{ needs.build.outputs.image_tag }}" >> $GITHUB_ENV
          else
            # Get the latest image tag from ECR
            REPO="${{ env.REPO_NAME }}-${{env.PLATFORM}}"
            LATEST_TAG=$(aws ecr describe-images --repository-name $REPO --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text)
            if [[ -z "$LATEST_TAG" ]]; then
              echo "No existing images found and build is skipped. Cannot proceed."
              exit 1
            fi
            echo "IMAGE_TAG=$LATEST_TAG" >> $GITHUB_ENV
          fi

      - name: Create Task Definition
        id: task-def
        run: |
          MIGRATE_SETUP='node -e "require('\''./generated/src/db/Migrations.bs.js'\'').setupDb()"'
          MIGRATE_UP='node -e "require('\''./generated/src/db/Migrations.bs.js'\'').runUpMigrations(true)"'
          MIGRATE_DOWN='node -e "require('\''./generated/src/db/Migrations.bs.js'\'').runDownMigrations(true)"'
          GRANT_PERMISSIONS='pnpm ts-node scripts/grant-aggregate-permissions.ts'
          RUN_INDEXER='TUI_OFF=true pnpm ts-node generated/src/Index.bs.js'

          case "${{ inputs.env }}" in
            "SETUP")
              CMD="$MIGRATE_SETUP && $GRANT_PERMISSIONS && $RUN_INDEXER"
              ;;
            "MIGRATE")
              CMD="$MIGRATE_UP && $RUN_INDEXER"
              ;;
            "FRESH")
              CMD="$MIGRATE_DOWN && $MIGRATE_UP && $RUN_INDEXER"
              ;;
            "UPDATE")
              CMD="$RUN_INDEXER"
              ;;
            *)
              echo "Invalid command type" && exit 1
              ;;
          esac

          # Get current task definition and remove AWS-specific fields
          aws ecs describe-task-definition --task-definition indexer-dev --query 'taskDefinition' > task-definition-full.json

          jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' task-definition-full.json > task-definition.json

          # Update the command and image in the indexer-dev container
          jq --arg cmd "$CMD" --arg img "${{ steps.login-ecr.outputs.registry }}/${{ env.REPO_NAME }}-${{env.PLATFORM}}:${{ env.IMAGE_TAG }}" '(.containerDefinitions[] | select(.name == "indexer-dev") | .command) = ["sh", "-c", $cmd] | (.containerDefinitions[] | select(.name == "indexer-dev") | .image) = $img' task-definition.json > updated-task-definition.json
          mv updated-task-definition.json task-definition.json

          # Store the task definition ARN
          echo "TASK_DEFINITION_ARN=$(aws ecs register-task-definition --cli-input-json file://task-definition.json --query 'taskDefinition.taskDefinitionArn' --output text)" >> $GITHUB_ENV

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{env.PLATFORM}}-services-cluster \
            --service ${{ env.REPO_NAME }}-${{env.PLATFORM}} \
            --task-definition ${{ env.TASK_DEFINITION_ARN }} \
            --force-new-deployment

      - name: Wait for service stability
        run: |
          aws ecs wait services-stable \
            --cluster ${{env.PLATFORM}}-services-cluster \
            --services ${{ env.REPO_NAME }}-${{env.PLATFORM}}

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: 'n-platform-deployments'
          config: .github/config/slack.yml
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          steps: ${{ toJson(steps) }}
        if: always()
